// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sys} from '../models';

export function AbrirArchivo():Promise<void>;

export function DeshabilitarUSB(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetCPUUsage():Promise<sys.CPUUsage>;

export function GetDISKUsage():Promise<sys.DISKUsage>;

export function GetRAMUsage():Promise<sys.RAMUsage>;

export function GetUSBPorts():Promise<Array<sys.USBport>>;

export function HabilitarUSB(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UsbLogs(arg1:string):Promise<void>;
