// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirArchivo() {
  return window['go']['sys']['Stats']['AbrirArchivo']();
}

export function DeshabilitarUSB(arg1, arg2, arg3) {
  return window['go']['sys']['Stats']['DeshabilitarUSB'](arg1, arg2, arg3);
}

export function GetCPUUsage() {
  return window['go']['sys']['Stats']['GetCPUUsage']();
}

export function GetDISKUsage() {
  return window['go']['sys']['Stats']['GetDISKUsage']();
}

export function GetRAMUsage() {
  return window['go']['sys']['Stats']['GetRAMUsage']();
}

export function GetUSBPorts() {
  return window['go']['sys']['Stats']['GetUSBPorts']();
}

export function HabilitarUSB(arg1, arg2, arg3) {
  return window['go']['sys']['Stats']['HabilitarUSB'](arg1, arg2, arg3);
}

export function UsbLogs(arg1) {
  return window['go']['sys']['Stats']['UsbLogs'](arg1);
}
