// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cpu() {
  return window['go']['main']['App']['Cpu']();
}

export function Disk() {
  return window['go']['main']['App']['Disk']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListUSB() {
  return window['go']['main']['App']['ListUSB']();
}

export function Ram() {
  return window['go']['main']['App']['Ram']();
}
