// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cpu():Promise<number>;

export function Disk():Promise<any>;

export function Greet(arg1:string):Promise<string>;
